### ISSUE TITLE
test app::components::preview_file::tests::works_with_one_arg hangs and does not finish

### ISSUE THREAD

**Issue by Absobel** [dzfrias/projectable#12]
When I run cargo test I just get : `test app::components::preview_file::tests::works_with_one_arg has been running for over 60 seconds` and it hangs

(Also I'm writing a PKGBUILD for addition to the Arch User Repository, is that okay ?)

**Comment by dzfrias** [comment]
Whoops. I think this is a weird subtlety between [cargo-nextest](https://nexte.st/) and `cargo test`, because nextest doesn't hang somehow. I'll fix the test, and thanks for letting me know! Thanks for writing something for the Arch User Repository, too!

**Comment by dzfrias** [comment]
Should be fixed with bf57de8822e068c1b9b83e19565518756e18c1a0! Let me know if the issue persists.

**Comment by Absobel** [comment]
Don't really want to open a whole issue just for that but this program is now on the AUR !

**Comment by dzfrias** [comment]
Thanks for your work! I don't really know how to contribute to something on the AUR, but after quickly scanning the PKGBUILD of the non `-git` version; it looks like I can update the version number and recompute the shasum. I don't have an account for Arch Linux though, and I can't get one because of the captcha.

Or, I see the "flag package-out-of-date", which I assume just notifies the maintainer.

**Comment by Absobel** [comment]
Yeah, I can do it, no problem 

If you manage to get an AUR account I can still put you as maintainer 

Yes the out of date flag notifies the maintainer and marks it when installing it through a AUR helper

**Comment by dzfrias** [comment]
Good to know! I was able to get an AUR account, under the name of "dzfrias". Thanks again for the work you've done!

**Comment by Absobel** [comment]
I updated the packages on the AUR. I'll add you as a maintainer ! (I can still do the maintaining job, it doesn't bother me at all :relieved: )

**Comment by dzfrias** [comment]
Sounds good!
